---
# basic configuration
MXNET_VERSION: "mxnet_v1.1.0"
gpus: '0,1,2,3'
plot: True
cudnn_tune: 'off'
workspace: 512
batch_per_device: 4
# input and output
output: "/mnt/truenas/scratch/yikangliao/output_liris_test"
df_test: '/mnt/truenas/scratch/yikangliao/dataset/LIRIS_D2/valid-df.pickle'
df_train: '/mnt/truenas/scratch/yikangliao/dataset/LIRIS_D2/train-df.pickle'
pretrained: '/mnt/truenas/scratch/yikangliao/pretrained_models/r2.5d_d18_l16.pkl'
# network related params
model_depth: 18
pooled_size: 10
final_spatial_kernel: 5
spatial_scale: 8
temporal_scale: 4
n_frame: 16
num_class: 10
scale_w: 180
scale_h: 144
n_bbox: 3
use_large_bbox: True
# training related params
num_epoch: 1000
optimizer: 'sgd'
lr: 0.00005
lr_step: 0
lr_factor: 0.1
warmup: False
warmup_lr: 0
warmup_step: 0
momentum: 0.9
bn_mom: 0.9
wd: 0.005
begin_epoch: 0
model_prefix: 'test'


